Incorporate reporting of emissions from agricultural residue burning
pik-piam/magpie4 pull request #10
Opened 2021-02-18 14:22 UTC by mscrawford

2021-02-18 14:27 UTC, tscheypidi requested changes

2021-02-18 14:27 UTC, tscheypidi commented on R/NitrogenBudget.R
> +    ash <- dimSums((readGDX(gdx,"ov_res_ag_burn","ov18_res_ag_burn",select=list(type="level"))[,,kcr]*(1-readGDX(gdx,"f18_res_combust_eff")[,,kcr]))[,,"nr"],dim=3)
I believe it must be `readGDX(..., format="first_found")` (you want to get either ov_res_ag_burn or ov18_res_ag_burn), right?

2021-02-18 14:27 UTC, tscheypidi commented on R/ResidueUsage.R
> +    Burn_kcr       <- collapseNames(readGDX(gdx,"ov_res_ag_burn","ov18_res_ag_burn")[,,"level"][,,"dm"])
same as above

2021-02-18 14:27 UTC, tscheypidi commented on DESCRIPTION
>  Authors@R: c(person("Benjamin Leon", "Bodirsky", email = "bodirsky@pik-potsdam.de", role = c("aut","cre")),
don't forget to add your name to the list of authors (forgot to mention that in mrcommons as well)

2021-02-18 14:27 UTC, tscheypidi commented on DESCRIPTION
>  Authors@R: c(person("Benjamin Leon", "Bodirsky", email = "bodirsky@pik-potsdam.de", role = c("aut","cre")),
also add your name in the author information of the functions to modify

2021-02-24 12:31 UTC, mscrawford commented
To follow up on this, I had to merge my changes into Abhi's subsequent changes. I added first_found to the readGDX calls as well as my name to the author list.

2021-02-24 12:33 UTC, tscheypidi approved these changes

2021-02-24 12:33 UTC, merged